Repository bla-bla-Notion/backend, pull requests merged in 2022-12, with the labels that each got.

#2 STYLE: 프로젝트 초기 세팅 완료 (#1)
  .eslintrc.js
  .gitignore
  .prettierrc.js
  app.js
  package-lock.json
  package.json
  yarn.lock
Labels: backend, project setting

#6 DOCS : socket.io 기본 코드 + 랜덤 닉네임 제너레이터 추가 (#3)
  .eslintrc.js
  package-lock.json
  package.json
  src/app.js
  src/assets/api.js
  src/assets/cart.html
  src/assets/detail.html
  src/assets/favicon.ico
  src/assets/goods.html
  src/assets/index.html
  src/assets/logo_big_tr.png
  src/assets/mystyle.css
  src/assets/order.html
  src/assets/register.html
  src/util/generateRandomName.util.js
  yarn.lock
Labels: backend, project setting

#10 FEAT : 백엔드 기본 스코프 개발 완료 - 예나버전
  package-lock.json
  package.json
  src/app.js
  src/public/js/front.js
  yarn.lock
Labels: backend, feature

#14 2차 테스트 배포용 PR 요청
  package-lock.json
  package.json
  src/app.js
  src/public/js/front.js
  yarn.lock
Labels: backend, deploy

#20 3 layered architecture를 통신 방법에 따라 나눔
  package-lock.json
  package.json
  src/app.js
  src/http/http.controller.js
  src/http/http.repository.js
  src/http/http.service.js
  src/routes/http.route.js
  src/routes/index.route.js
  src/routes/socket.route.js
  src/schemas/index.schema.js
  src/socket/socket.controller.js
  src/socket/socket.repository.js
  src/socket/socket.service.js
  yarn.lock
Labels: backend, project setting

#21 DOCS : socket practice 연수
  .eslintrc.js
  package-lock.json
  package.json
  src/app.js
  src/public/js/front.js
  yarn.lock
Labels: backend, feature

#28 FEAT : 커스텀 에러 객체, 에러 핸들러 및 로거 적용
  src/app.js
  src/exceptions/index.exception.js
  src/http/http.controller.js
  src/middlewares/error-handler.middleware.js
Labels: backend, project setting, feature

#31 기본 url 접속시 page list 보여주기
  src/app.js
  src/http/http.controller.js
  src/http/http.repository.js
  src/http/http.service.js
  src/routes/http.route.js
  src/routes/index.route.js
  src/schemas/index.schema.js
Labels: backend, feature

#35 auto save 구현, page 관련 api 개발 후 배포버전 문제 해결
  src/app.js
  src/http/http.controller.js
  src/http/http.service.js
  src/util/autoSavePage.util.js
Labels: backend, feature, fix
